config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do

  resources :pages do
    resources :elements do
      resources :properties
    end
  end

  get 'edit_elements/:id' => "elements#edit", :as => :element
  put 'edit_elements/:id' => "elements#edit", :as => :element
  post 'pages/:id/create_element' => "elements#create_element", :as => :create_element
  post 'pages/:id/destroy_each' => "elements#destroy_each", :as => :destroy_each
  get 'admin_pages' => "pages#admin_pages", :as => :admin_pages
  get 'pages/:id/element_list' => "pages#element_list", :as => :element_list

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

   # Feel free to change '/admin' to any namespace you need.
  authenticated :user do
    root :to => 'pages#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/views/pages/_form.html.erb
<%= simple_form_for(@page) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pages/admin_pages.html.erb
<h3>Pages</h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>User Name</th>
      <th>App Name</th>
      <th>Creation Time</th>
      <th>User Role</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @pages.each do |page| %>
    <tr>
      <td><%= page.user.name %></td>
      <td><%= page.name %></td>
      <td><%= page.created_at.to_date %></td>
      <td><%= page.user.roles.first.name.titleize unless page.user.roles.first.nil? %></td>
      <td>
        <%= link_to("Change Content", element_list_path(page), :class => 'btn btn-mini')%>
      </td>
      <td><%= link_to("Delete Page", page_path(page), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini')%></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path, :class => "button"  %>

app/views/pages/element_list.html.erb
<div class="span12">
<div class="span5">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @elements.each do |element| %>
    <tr>
      <td><%= element.name %></td>
      <td>
        <%= link_to("Change Content", edit_page_element_path(@page, element), :class => 'btn btn-mini')%>
      </td>
      <td><%= link_to("Delete", page_element_path(@page, element), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini')%></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>
</div>
<%= link_to("Back", admin_pages_path, :class => 'btn btn-mini')%>

app/views/pages/index.html.erb
<h1>App Salamander</h1>
<% if current_user.present? %>
  <%= image_tag(current_user.image_url,:size => "100x100", :alt =>'No image' ,:style =>"float:right;")%>
<% end %>
<div id="signup" style="display:none;">
  <%= simple_form_for(Page.new) do |f| %>
    <div class="form-inputs">
      <%= f.input :name, :label => 'App Name', :class => "text ui-widget-content ui-corner-all" %>
    </div>

    <div>
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

<div>
  <span>
    <%= link_to image_tag('default.png'), 'javascript:void(0);', :onclick => "javascript:$( '#signup' ).dialog( 'open' )"%>
  </span>
</div>
<br/>
<br/>
<% if @pages.count > 0 %>
  <h1>My Apps</h1>
<% end %>
<div id="canvas">
  <% @pages.each do |page| %>
    <div style="width:145px;float:left;margin-left:35px;">
      <%= link_to image_tag('delete.png', :style => 'position: relative; top:14px; left:14px;float:right;'), page_path(page), method: :delete, data: { confirm: 'Are you sure?' } %>
      <script type="text/javascript">
        wsr_snapshot('<%= page_url(page) %>', 'M79FaWp0Rm35', 's');
      </script>
      <br/>
        <div style="text-align:center"><%= page.name %></div>
    </div>
  <% end %>
</div>
<br />
<script type="text/javascript">
  $(document).ready(function() {
    $('#canvas a').each(function() {
      $(this).attr('onmousedown', '');
      $(this).attr('target', '');
    })
  });  

  $( "#signup" ).dialog({
    autoOpen: false,
    height: 180,
    width: 250,
    modal: true
  });

  
</script>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path, :class => "button" %>