config/routes.rb
Rails3BootstrapDeviseCancan::Application.routes.draw do

  resources :pages do
    resources :elements do
      resources :properties
    end
  end

  get 'edit_elements/:id' => "elements#edit", :as => :element
  put 'edit_elements/:id' => "elements#edit", :as => :element
  post 'pages/:id/create_element' => "elements#create_element", :as => :create_element
  post 'pages/:id/destroy_each' => "elements#destroy_each", :as => :destroy_each
  get 'admin_pages' => "pages#admin_pages", :as => :admin_pages
  get 'pages/:id/element_list' => "pages#element_list", :as => :element_list

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

   # Feel free to change '/admin' to any namespace you need.
  authenticated :user do
    root :to => 'pages#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "SALAMANDER", root_path, :class => 'brand' %>
<div class="dropdown">
  <a class="account" >
    <span>My Account</span>
  </a>
  <div class="submenu" style="display: none; ">
    <ul class="root">
      <% if user_signed_in? %>
        <li>
          <%= link_to 'Apps', pages_path %>
        </li>
        <li>
          <%= link_to 'Edit account', edit_user_registration_path %>
        </li>
        <% if current_user.has_role? :admin %>
          <li>
            <%= link_to 'Edit users', users_path %>
          </li>
        <% end %>
        <li>
          <%= link_to 'Edit elements', admin_pages_path %>
        </li>
        <li>
          <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
        </li>
      <% else %>
        <li>
          <%= link_to 'Login', new_user_session_path %>
        </li>
        <li>
          <%= link_to 'Sign up', new_user_registration_path %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "UICreation" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails3 Bootstrap Devise Cancan" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <script type="text/javascript" src="http://www.websnapr.com/js/websnapr.js"></script>
    <script type="text/javascript" src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>